# Generated by Django 6.0.3 on 2026-03-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark_api', '0002_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingsessions',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
